export const siteConfig = {
  name: "Paola Ramirez",
  title: "Líder en Transformación Digital & Excelencia Operativa",
  description: "Portfolio de Paola Ramirez - Líder Estratégico en Transformación Digital, Gobierno de Procesos y Gestión del Cambio con +13 años de experiencia en Latam",
  accentColor: "#1e3a5f",
  social: {
    email: "paolarago2@gmail.com",
    linkedin: "https://linkedin.com/in/paolaramirezgonzales",
  },
  aboutMe:
    "Especialista en diseño e implementación de marcos de gobierno, estandarización de procesos, estrategias de transformación digital end-to-end y gestión del cambio organizacional. Con más de 13 años de experiencia asegurando crecimiento de ingresos, productividad sostenida y madurez digital en sectores como Consumo Masivo, Banca y Finanzas, Salud, Retail y Logística. Alcance internacional en Perú, Latinoamérica y Centroamérica.",
  skills: [
    "Transformación Digital",
    "Lean",
    "Agile",
    "SCRUM",
    "PMO",
    "ITIL",
    "COBIT",
    "Design Thinking",
    "Customer Experience",
    "Change Management",
    "Power BI",
    "Data Analytics",
    "Gobierno de Procesos",
    "Service Design",
  ],
  projects: [],
  experience: [
    {
      company: "CBC – Grupo Mariposa",
      title: "Especialista de Procesos y Change Management",
      dateRange: "Jul 2024 - Dic 2025",
      bullets: [
        "Liderazgo de procesos, gobierno del ciclo comercial y transformación digital para 7 países (Guatemala, Ecuador, Perú, El Salvador, Honduras, Nicaragua, Jamaica)",
        "Rediseño y despliegue del Ciclo Comercial Integral (procesos, procedimientos, reuniones, roles) transformando la operación de base regional",
        "Reestructuración del rol de Supervisor de Ventas (+300 a nivel corporativo) potenciando sus capacidades digitales",
        "Desarrollo de ecosistema digital con Suite Microsoft impactando a +350 colaboradores en 6 países",
        "Liderazgo de 4 sesiones corporativas 'Train the Trainers' con +300 asistentes cada una",
      ],
    },
    {
      company: "Alicorp",
      title: "Portfolio Manager de Finanzas y RRHH",
      dateRange: "Jul 2022 - Abr 2024",
      bullets: [
        "Gestión estratégica del portafolio de proyectos para 5 subsidiarias (Perú, Bolivia, Ecuador, Chile, Uruguay)",
        "Administración de presupuesto consolidado de +3.4M USD sin desvíos significativos",
        "Supervisión de +50 iniciativas de Finanzas, Contraloría, RRHH, Nómina y TI",
        "Reducción de 1 día en el cierre contable consolidado a nivel corporativo",
        "Implementación del modelo integral de gestión de programas como referente regional",
      ],
    },
    {
      company: "Stefanini IT Solutions",
      title: "Consultor de Procesos y Tecnología",
      dateRange: "Feb 2022 - May 2022",
      bullets: [
        "Consultoría estratégica para UNACEM en diagnóstico y rediseño de arquitectura de procesos de TI",
        "Diseño de marco de gobierno integral aplicando COBIT e ITIL",
        "Entrega de nueva estructura de procesos de TI como hoja de ruta para la transformación del área",
      ],
    },
    {
      company: "Grupo Vital Salud",
      title: "Jefe de Operaciones y Mejora Continua",
      dateRange: "Ene 2021 - Nov 2021",
      bullets: [
        "Liderazgo del plan estratégico, gobierno de procesos y gestión de servicios para +15 unidades mineras (Chinalco, Barrick, Angloamerican)",
        "Optimización de estructura organizacional logrando eficiencia del 25% en número de puestos y planilla",
        "Automatización de procesos reduciendo gestión administrativa en 70% y eliminando 85% de quejas por retrasos",
        "Gestión integral de equipo de 13 personas con control presupuestal del área",
      ],
    },
    {
      company: "Consultoría Independiente",
      title: "Consultor Senior de Innovación y Transformación",
      dateRange: "Oct 2020 - Ene 2021",
      bullets: [
        "Implementación del área de Innovación para Grupo Alfa (Sector Industrial) con plan estratégico y portafolio de proyectos",
        "Diseño e implementación del marco de gestión de proyectos de TI para Pulso Salud (Sector Salud)",
        "Capacitación a áreas comerciales en metodologías Agile y Customer Experience",
      ],
    },
    {
      company: "Banco de Crédito del Perú (BCP)",
      title: "Subgerente de Consultoría, Métodos y Prácticas Lean y Agile",
      dateRange: "Nov 2017 - Dic 2019",
      bullets: [
        "Liderazgo de transformación cultural hacia modelo ágil a escala organizacional",
        "Proyecto VTAPO: reducción del 80% en tiempo de capacitación y traspaso (40 días-hombre)",
        "Reducción del 10% en tiempos de atención de reclamos en Operaciones",
        "Incremento del 14% en productividad de áreas de Operaciones y Banca Minorista",
        "Capacitación a líderes en diseño de Squads/OKRs para Tribus de Negocios y Seguros",
      ],
    },
    {
      company: "AFP Integra",
      title: "Analista Senior de Proyectos y Tecnología",
      dateRange: "Jul 2016 - Sep 2017",
      bullets: [
        "Implementación de proyectos estratégicos de BI/BA (IBM InfoSphere, Qlikview, Power BI)",
        "Optimización del 57% en horas-hombre para análisis de datos mediante construcción de Data Marts",
        "Reducción del 35% en tiempos de entrega aplicando SCRUM",
        "Ahorro del 10% en presupuesto global de proyectos gestionados",
        "Cumplimiento normativo SOX sin observaciones de auditoría",
      ],
    },
    {
      company: "Albis S.A.",
      title: "Analista de Planeamiento Estratégico y BI",
      dateRange: "Mar 2015 - Feb 2016",
      bullets: [
        "Desarrollo de soluciones de Business Intelligence para la industria farmacéutica",
        "Análisis estratégico y proyecciones para la toma de decisiones gerenciales",
      ],
    },
  ],
  education: [
    {
      school: "Centrum PUCP",
      degree: "Maestría en Gerencia de Tecnologías de la Información",
      dateRange: "En curso",
      achievements: [],
    },
    {
      school: "Centrum PUCP",
      degree: "MBA - Maestría en Administración Estratégica de Empresas",
      dateRange: "2022 - 2024",
      achievements: [],
    },
    {
      school: "EADA Business School Barcelona",
      degree: "Programa Avanzado en Big Data & Analytics",
      dateRange: "2024",
      achievements: [],
    },
    {
      school: "Universidad Peruana de Ciencias Aplicadas (UPC)",
      degree: "Ingeniería Industrial",
      dateRange: "2015",
      achievements: [],
    },
  ],
};
